Repository wecode-bootcamp-korea/37-1st-Melon-Plate-backend, pull requests merged in 2022-09, with the labels that each got.

#1 멜론플레이트 back 초기 세팅
  .env.sample
  .gitignore
  app.js
  db/migrations/20220919091528_create_users_table.sql
  db/migrations/20220919091535_create_stores_table.sql
  db/migrations/20220919091542_create_comments_table.sql
  db/migrations/20220919091854_create_comments_table.sql
  package-lock.json
  package.json
  plate.csv
  src/controllers/index.js
  src/middleware/index.js
  src/models/index.js
  src/routes/index.js
  src/services/index.js
Labels: 수정 요청

#2 회원가입 구현
  .DS_Store
  .env.sample
  .gitignore
  app.js
  db/.DS_Store
  db/migrations/20220919091528_create_users_table.sql
  db/migrations/20220919091535_create_stores_table.sql
  db/migrations/20220919091542_create_comments_table.sql
  db/migrations/20220919091854_create_comments_table.sql
  db/migrations/20220920072819_create_users_table.sql
  db/migrations/20220920083133_create_days_tables.sql
  db/migrations/20220920083134_create_stores_tables.sql
  db/migrations/20220920083406_create_likes_tables.sql
  db/migrations/20220920084535_create_menus_tables.sql
  db/migrations/20220920084706_create_reviews_tables.sql
  db/migrations/20220920084726_create_review_images_tables.sql
  db/migrations/20220920084814_create_categories_tables.sql
  db/migrations/20220920084815_create_store_infos_tables.sql
  package-lock.json
  package.json
  plate.csv
  src/controllers/index.js
  src/controllers/userController.js
  src/middleware/index.js
  src/middlewares/errorHandler.js
  src/middlewares/index.js
  src/middlewares/uploadFiles.js
  src/middlewares/validators.js
  src/models/dataSource.js
  src/models/index.js
  src/models/userDao.js
  src/routes/index.js
  src/routes/userRouter.js
  src/services/index.js
  src/services/userService.js
Labels: 멘토 리뷰 요청

#6 db 재설정정
  .gitignore
  db/migrations/20220920072040_create_categories_table.sql
  db/migrations/20220920083134_create_menus_tables.sql
  db/migrations/20220920083135_create_stores_tables.sql
  db/migrations/20220920084815_create_store_infos_tables.sql
  db/migrations/20220920084815_create_store_menus_tables.sql
  db/migrations/20220923075240_create_off_days_table.sql
Labels: 완료

#7 검색 기능 구현
  .DS_Store
  .gitignore
  app.js
  db/migrations/20220920083134_create_menus_tables.sql
  src/controllers/index.js
  src/controllers/mainController.js
  src/controllers/userController.js
  src/middlewares/auth.js
  src/models/index.js
  src/models/mainDao.js
  src/routes/index.js
  src/routes/mainRouter.js
  src/services/index.js
  src/services/mainService.js
  src/services/userService.js
Labels: 멘토 리뷰 요청

#8 [김응수] 사장님 회원가입 / 로그인 / 맛집 관리 기능 구현
  .env.sample
  .gitignore
  app.js
  package-lock.json
  package.json
  src/controllers/index.js
  src/controllers/storeController.js
  src/controllers/userController.js
  src/middlewares/auth.js
  src/middlewares/index.js
  src/middlewares/multer.js
  src/middlewares/uploadFiles.js
  src/models/dataSource.js
  src/models/index.js
  src/models/storeDao.js
  src/models/userDao.js
  src/routes/index.js
  src/routes/storeRouter.js
  src/routes/userRouter.js
  src/services/index.js
  src/services/storeService.js
  src/services/userService.js
Labels: 멘토 리뷰 요청

#10 메뉴, 리뷰 테이블 수정 및 검색 기능 로직 수정
  app.js
  db/migrations/20220920084706_create_reviews_tables.sql
  db/migrations/20220920084815_create_store_menus_tables.sql
  db/migrations/20220920085134_create_menus_tables.sql
  src/controllers/mainController.js
  src/models/mainDao.js
  src/services/mainService.js
Labels: 멘토 리뷰 요청

#13 리스트 피드백 수정, 검색 필터링 구현
  src/controllers/index.js
  src/controllers/listController.js
  src/middlewares/auth.js
  src/middlewares/index.js
  src/models/index.js
  src/models/listDao.js
  src/models/mainDao.js
  src/routes/index.js
  src/routes/listRouter.js
  src/services/index.js
  src/services/listService.js
Labels: 멘토 리뷰 요청

#12 [김응수] 좋아요(가고싶다) 기능 추가
  app.js
  db/migrations/20220920085313_create_menus_tables.sql
  src/controllers/index.js
  src/controllers/likeController.js
  src/controllers/storeController.js
  src/controllers/userController.js
  src/middlewares/auth.js
  src/middlewares/index.js
  src/models/index.js
  src/models/likeDao.js
  src/models/storeDao.js
  src/models/userDao.js
  src/routes/index.js
  src/routes/likeRouter.js
  src/routes/storeRouter.js
  src/services/index.js
  src/services/likeService.js
  src/services/storeService.js
Labels: 멘토 리뷰 요청

#11 리뷰 기능 구현
  .DS_Store
  .gitignore
  db/migrations/20220920084726_create_review_images.sql
  package-lock.json
  package.json
  src/controllers/index.js
  src/controllers/reviewController.js
  src/middlewares/auth.js
  src/middlewares/index.js
  src/middlewares/multer.js
  src/models/index.js
  src/models/reviewDao.js
  src/routes/index.js
  src/routes/reviewRouter.js
  src/routes/userRouter.js
  src/services/index.js
  src/services/reviewService.js
Labels: 멘토 리뷰 요청

#14 검색 기능과 리스트 기능 통합 구현
  src/controllers/mainController.js
  src/models/mainDao.js
  src/services/mainService.js
Labels: 멘토 리뷰 요청

#17 [김응수] 디테일페이지 및 리뷰페이지
  src/controllers/detailController.js
  src/controllers/userController.js
  src/middlewares/auth.js
  src/models/detailDao.js
  src/models/index.js
  src/models/reviewDao.js
  src/models/userDao.js
  src/routes/detailRouter.js
  src/routes/storeRouter.js
  src/services/detailService.js
  src/services/index.js
Labels: 멘토 리뷰 요청
